<?php

/**
 * This is the model base class for the table "program".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Program".
 *
 * Columns in table "program" available as properties of the model,
 * followed by relations of table "program" available as properties of the model.
 *
 * @property string $id
 * @property string $name
 * @property string $slug
 *
 * @property Course[] $courses
 */
abstract class BaseProgram extends AActiveRecord
{

    public function getTextColumns()
    {
        return array();
    }

    public function tableName()
    {
        return 'program';
    }

    public static function label($n = 1)
    {
        return Yii::t('admin', 'Program|Programs', $n);
    }

    public static function representingColumn()
    {
        return 'slug';
    }

    public function rules()
    {
        return array(
            array('slug', 'required'),
            array('name, slug', 'length', 'max'=>32),
            array('name', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, name, slug', 'safe', 'on' => 'search'),
        );
    }

    public function relations()
    {
        return array(
            'courses' => array(self::HAS_MANY, 'Course', 'program_id'),
        );
    }

    public function pivotModels()
    {
        return array(
        );
    }

    public function attributeLabels()
    {
        return array(
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'slug' => Yii::t('app', 'Slug'),
            'courses' => null,
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id, true);
        $criteria->compare('name', $this->name, true);
        $criteria->compare('slug', $this->slug, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}