<?php

/**
 * This is the model base class for the table "user_award".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserAward".
 *
 * Columns in table "user_award" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $user_id
 * @property string $award_id
 * @property string $time
 *
 */
abstract class BaseUserAward extends AActiveRecord
{

    public function getTextColumns()
    {
        return array();
    }

    public function tableName()
    {
        return 'user_award';
    }

    public static function label($n = 1)
    {
        return Yii::t('admin', 'UserAward|UserAwards', $n);
    }

    public static function representingColumn()
    {
        return array(
            'user_id',
            'award_id',
        );
    }

    public function rules()
    {
        return array(
            array('user_id, award_id, time', 'required'),
            array('user_id, award_id', 'length', 'max'=>10),
            array('user_id, award_id, time', 'safe', 'on' => 'search'),
        );
    }

    public function relations()
    {
        return array(
        );
    }

    public function pivotModels()
    {
        return array(
        );
    }

    public function attributeLabels()
    {
        return array(
            'user_id' => null,
            'award_id' => null,
            'time' => Yii::t('app', 'Time'),
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('user_id', $this->user_id);
        $criteria->compare('award_id', $this->award_id);
        $criteria->compare('time', $this->time, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}