<?php

/**
 * This is the model base class for the table "material_subject".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MaterialSubject".
 *
 * Columns in table "material_subject" available as properties of the model,
 * followed by relations of table "material_subject" available as properties of the model.
 *
 * @property string $id
 * @property string $name
 * @property string $slug
 *
 * @property Material[] $materials
 */
abstract class BaseMaterialSubject extends AActiveRecord
{

    public function getTextColumns()
    {
        return array();
    }

    public function tableName()
    {
        return 'material_subject';
    }

    public static function label($n = 1)
    {
        return Yii::t('admin', 'MaterialSubject|MaterialSubjects', $n);
    }

    public static function representingColumn()
    {
        return 'slug';
    }

    public function rules()
    {
        return array(
            array('slug', 'required'),
            array('name', 'length', 'max'=>64),
            array('slug', 'length', 'max'=>32),
            array('name', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, name, slug', 'safe', 'on' => 'search'),
        );
    }

    public function relations()
    {
        return array(
            'materials' => array(self::HAS_MANY, 'Material', 'subject_id'),
        );
    }

    public function pivotModels()
    {
        return array(
        );
    }

    public function attributeLabels()
    {
        return array(
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'slug' => Yii::t('app', 'Slug'),
            'materials' => null,
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id, true);
        $criteria->compare('name', $this->name, true);
        $criteria->compare('slug', $this->slug, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}