<?php

/**
 * This is the model base class for the table "user_mark".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserMark".
 *
 * Columns in table "user_mark" available as properties of the model,
 * followed by relations of table "user_mark" available as properties of the model.
 *
 * @property string $user_id
 * @property string $subject_id
 * @property integer $mark
 * @property string $time
 *
 * @property User $user
 * @property Subject $subject
 */
abstract class BaseUserMark extends AActiveRecord
{

    public function getTextColumns()
    {
        return array();
    }

    public function tableName()
    {
        return 'user_mark';
    }

    public static function label($n = 1)
    {
        return Yii::t('admin', 'UserMark|UserMarks', $n);
    }

    public static function representingColumn()
    {
        return 'time';
    }

    public function rules()
    {
        return array(
            array('user_id, time', 'required'),
            array('mark', 'numerical', 'integerOnly'=>true),
            array('user_id, subject_id', 'length', 'max'=>10),
            array('subject_id, mark', 'default', 'setOnEmpty' => true, 'value' => null),
            array('user_id, subject_id, mark, time', 'safe', 'on' => 'search'),
        );
    }

    public function relations()
    {
        return array(
            'user' => array(self::BELONGS_TO, 'User', 'user_id'),
            'subject' => array(self::BELONGS_TO, 'Subject', 'subject_id'),
        );
    }

    public function pivotModels()
    {
        return array(
        );
    }

    public function attributeLabels()
    {
        return array(
            'user_id' => null,
            'subject_id' => null,
            'mark' => Yii::t('app', 'Mark'),
            'time' => Yii::t('app', 'Time'),
            'user' => null,
            'subject' => null,
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('user_id', $this->user_id);
        $criteria->compare('subject_id', $this->subject_id);
        $criteria->compare('mark', $this->mark);
        $criteria->compare('time', $this->time, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}