<?php

/**
 * This is the model base class for the table "rank".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Rank".
 *
 * Columns in table "rank" available as properties of the model,
 * followed by relations of table "rank" available as properties of the model.
 *
 * @property string $id
 * @property string $name
 * @property string $permissions
 * @property string $parent_group_id
 * @property string $ts_group_id
 * @property string $type
 * @property integer $order
 *
 * @property Course[] $courses
 * @property Course[] $courses1
 * @property Rank $parentGroup
 * @property Rank[] $ranks
 * @property User[] $users
 * @property User[] $users1
 */
abstract class BaseRank extends AActiveRecord
{
    const PERMISSIONS_ADMIN = 'admin';
    const TYPE_RANK = 'rank';
    const TYPE_INSTRUCTOR = 'instructor';
    const TYPE_HIDDEN = 'hidden';

    public function getSetValueText($column, $value = null)
    {
        $texts = array(
            'permissions' => array(
                'admin' => Yii::t('app', 'Admin'),
            ),
            'type' => array(
                'rank' => Yii::t('app', 'Rank'),
                'instructor' => Yii::t('app', 'Instructor'),
                'hidden' => Yii::t('app', 'Hidden'),
            ),
        );

        if ($value)
            return $texts[$column][$value];

        return $texts[$column];
    }

    public function getTextColumns()
    {
        return array();
    }

    public function tableName()
    {
        return 'rank';
    }

    public static function label($n = 1)
    {
        return Yii::t('admin', 'Rank|Ranks', $n);
    }

    public static function representingColumn()
    {
        return 'name';
    }

    public function rules()
    {
        return array(
            array('order', 'numerical', 'integerOnly'=>true),
            array('name', 'length', 'max'=>32),
            array('parent_group_id, ts_group_id, type', 'length', 'max'=>10),
            array('permissions', 'safe'),
            array('name, permissions, parent_group_id, ts_group_id, type, order', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, name, permissions, parent_group_id, ts_group_id, type, order', 'safe', 'on' => 'search'),
        );
    }

    public function relations()
    {
        return array(
            'courses' => array(self::HAS_MANY, 'Course', 'rank_id'),
            'courses1' => array(self::HAS_MANY, 'Course', 'next_rank_id'),
            'parentGroup' => array(self::BELONGS_TO, 'Rank', 'parent_group_id'),
            'ranks' => array(self::HAS_MANY, 'Rank', 'parent_group_id'),
            'users' => array(self::HAS_MANY, 'User', 'rank_id'),
            'users1' => array(self::HAS_MANY, 'User', 'instructor_id'),
        );
    }

    public function pivotModels()
    {
        return array(
        );
    }

    public function attributeLabels()
    {
        return array(
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'permissions' => Yii::t('app', 'Permissions'),
            'parent_group_id' => null,
            'ts_group_id' => Yii::t('app', 'Ts Group'),
            'type' => Yii::t('app', 'Type'),
            'order' => Yii::t('app', 'Order'),
            'courses' => null,
            'courses1' => null,
            'parentGroup' => null,
            'ranks' => null,
            'users' => null,
            'users1' => null,
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id, true);
        $criteria->compare('name', $this->name, true);
        $criteria->compare('permissions', $this->permissions, true);
        $criteria->compare('parent_group_id', $this->parent_group_id);
        $criteria->compare('ts_group_id', $this->ts_group_id, true);
        $criteria->compare('type', $this->type, true);
        $criteria->compare('order', $this->order);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}