<?php

/**
 * This is the model base class for the table "text".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Text".
 *
 * Columns in table "text" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $title
 * @property string $text
 *
 */
abstract class BaseText extends AActiveRecord
{

    public function getTextColumns()
    {
        return array();
    }

    public function tableName()
    {
        return 'text';
    }

    public static function label($n = 1)
    {
        return Yii::t('admin', 'Text|Texts', $n);
    }

    public static function representingColumn()
    {
        return 'title';
    }

    public function rules()
    {
        return array(
            array('title', 'required'),
            array('title', 'length', 'max'=>128),
            array('text', 'safe'),
            array('text', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, title, text', 'safe', 'on' => 'search'),
        );
    }

    public function relations()
    {
        return array(
        );
    }

    public function pivotModels()
    {
        return array(
        );
    }

    public function attributeLabels()
    {
        return array(
            'id' => Yii::t('app', 'ID'),
            'title' => Yii::t('app', 'Title'),
            'text' => Yii::t('app', 'Text'),
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id, true);
        $criteria->compare('title', $this->title, true);
        $criteria->compare('text', $this->text, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}