<?php

/**
 * This is the model base class for the table "user".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "User".
 *
 * Columns in table "user" available as properties of the model,
 * followed by relations of table "user" available as properties of the model.
 *
 * @property string $id
 * @property string $nickname
 * @property string $firstname
 * @property string $email
 * @property string $password
 * @property string $ts_id
 * @property string $join_date
 * @property string $birth_date
 * @property string $roster
 * @property string $rank_id
 * @property string $instructor_id
 * @property string $ip
 * @property string $is_clanner
 * @property string $is_technician
 * @property string $img_src
 * @property string $qualifications
 * @property string $last_online_time
 * @property string $broadcast_token
 * @property string $recovery_token
 * @property integer $is_disabled
 * @property string $disable_reason
 * @property string $last_warning_time
 * @property integer $is_defector
 *
 * @property BattleEvent[] $battleEvents
 * @property ForumMessage[] $forumMessages
 * @property ForumTopic[] $forumTopics
 * @property News[] $news
 * @property Notification[] $notifications
 * @property Order[] $orders
 * @property PrivateMessage[] $privateMessages
 * @property PrivateMessage[] $privateMessages1
 * @property Rank $rank
 * @property Rank $instructor
 * @property Award[] $awards
 * @property UserEvent[] $userEvents
 * @property UserMark[] $userMarks
 * @property UserMark[] $userMarks1
 * @property Vacation[] $vacations
 */
abstract class BaseUser extends AActiveRecord
{
    const QUALIFICATIONS_FIGHTER = 'fighter';
    const QUALIFICATIONS_BOMBER = 'bomber';

    public function getSetValueText($column, $value = null)
    {
        $texts = array(
            'qualifications' => array(
                'fighter' => Yii::t('app', 'Fighter'),
                'bomber' => Yii::t('app', 'Bomber'),
            ),
        );

        if ($value)
            return $texts[$column][$value];

        return $texts[$column];
    }

    public function getTextColumns()
    {
        return array();
    }

    public function tableName()
    {
        return 'user';
    }

    public static function label($n = 1)
    {
        return Yii::t('admin', 'User|Users', $n);
    }

    public static function representingColumn()
    {
        return 'qualifications';
    }

    public function rules()
    {
        return array(
            array('is_disabled, is_defector', 'numerical', 'integerOnly'=>true),
            array('nickname, password, ip, broadcast_token, recovery_token', 'length', 'max'=>32),
            array('firstname', 'length', 'max'=>128),
            array('email, ts_id', 'length', 'max'=>64),
            array('rank_id, instructor_id, img_src', 'length', 'max'=>10),
            array('is_clanner, is_technician', 'length', 'max'=>1),
            array('join_date, birth_date, roster, qualifications, last_online_time, disable_reason, last_warning_time', 'safe'),
            array('nickname, firstname, email, password, ts_id, join_date, birth_date, roster, rank_id, instructor_id, ip, is_clanner, is_technician, img_src, qualifications, last_online_time, broadcast_token, recovery_token, is_disabled, disable_reason, last_warning_time, is_defector', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, nickname, firstname, email, password, ts_id, join_date, birth_date, roster, rank_id, instructor_id, ip, is_clanner, is_technician, img_src, qualifications, last_online_time, broadcast_token, recovery_token, is_disabled, disable_reason, last_warning_time, is_defector', 'safe', 'on' => 'search'),
        );
    }

    public function relations()
    {
        return array(
            'battleEvents' => array(self::HAS_MANY, 'BattleEvent', 'user_id'),
            'forumMessages' => array(self::HAS_MANY, 'ForumMessage', 'author_id'),
            'forumTopics' => array(self::HAS_MANY, 'ForumTopic', 'author_id'),
            'news' => array(self::HAS_MANY, 'News', 'issuer_id'),
            'notifications' => array(self::HAS_MANY, 'Notification', 'user_id'),
            'orders' => array(self::MANY_MANY, 'Order', 'order_participant(user_id, order_id)'),
            'privateMessages' => array(self::HAS_MANY, 'PrivateMessage', 'reciever_id'),
            'privateMessages1' => array(self::HAS_MANY, 'PrivateMessage', 'sender_id'),
            'rank' => array(self::BELONGS_TO, 'Rank', 'rank_id'),
            'instructor' => array(self::BELONGS_TO, 'Rank', 'instructor_id'),
            'awards' => array(self::MANY_MANY, 'Award', 'user_award(user_id, award_id)'),
            'userEvents' => array(self::HAS_MANY, 'UserEvent', 'user_id'),
            'userMarks' => array(self::HAS_MANY, 'UserMark', 'user_id'),
            'userMarks1' => array(self::HAS_MANY, 'UserMark', 'issuer_id'),
            'vacations' => array(self::HAS_MANY, 'Vacation', 'user_id'),
        );
    }

    public function pivotModels()
    {
        return array(
            'orders' => 'OrderParticipant',
            'awards' => 'UserAward',
        );
    }

    public function attributeLabels()
    {
        return array(
            'id' => Yii::t('app', 'ID'),
            'nickname' => Yii::t('app', 'Nickname'),
            'firstname' => Yii::t('app', 'Firstname'),
            'email' => Yii::t('app', 'Email'),
            'password' => Yii::t('app', 'Password'),
            'ts_id' => Yii::t('app', 'Ts'),
            'join_date' => Yii::t('app', 'Join Date'),
            'birth_date' => Yii::t('app', 'Birth Date'),
            'roster' => Yii::t('app', 'Roster'),
            'rank_id' => null,
            'instructor_id' => null,
            'ip' => Yii::t('app', 'Ip'),
            'is_clanner' => Yii::t('app', 'Is Clanner'),
            'is_technician' => Yii::t('app', 'Is Technician'),
            'img_src' => Yii::t('app', 'Img Src'),
            'qualifications' => Yii::t('app', 'Qualifications'),
            'last_online_time' => Yii::t('app', 'Last Online Time'),
            'broadcast_token' => Yii::t('app', 'Broadcast Token'),
            'recovery_token' => Yii::t('app', 'Recovery Token'),
            'is_disabled' => Yii::t('app', 'Is Disabled'),
            'disable_reason' => Yii::t('app', 'Disable Reason'),
            'last_warning_time' => Yii::t('app', 'Last Warning Time'),
            'is_defector' => Yii::t('app', 'Is Defector'),
            'battleEvents' => null,
            'forumMessages' => null,
            'forumTopics' => null,
            'news' => null,
            'notifications' => null,
            'orders' => null,
            'privateMessages' => null,
            'privateMessages1' => null,
            'rank' => null,
            'instructor' => null,
            'awards' => null,
            'userEvents' => null,
            'userMarks' => null,
            'userMarks1' => null,
            'vacations' => null,
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id, true);
        $criteria->compare('nickname', $this->nickname, true);
        $criteria->compare('firstname', $this->firstname, true);
        $criteria->compare('email', $this->email, true);
        $criteria->compare('password', $this->password, true);
        $criteria->compare('ts_id', $this->ts_id, true);
        $criteria->compare('join_date', $this->join_date, true);
        $criteria->compare('birth_date', $this->birth_date, true);
        $criteria->compare('roster', $this->roster, true);
        $criteria->compare('rank_id', $this->rank_id);
        $criteria->compare('instructor_id', $this->instructor_id);
        $criteria->compare('ip', $this->ip, true);
        $criteria->compare('is_clanner', $this->is_clanner, true);
        $criteria->compare('is_technician', $this->is_technician, true);
        $criteria->compare('img_src', $this->img_src, true);
        $criteria->compare('qualifications', $this->qualifications, true);
        $criteria->compare('last_online_time', $this->last_online_time, true);
        $criteria->compare('broadcast_token', $this->broadcast_token, true);
        $criteria->compare('recovery_token', $this->recovery_token, true);
        $criteria->compare('is_disabled', $this->is_disabled);
        $criteria->compare('disable_reason', $this->disable_reason, true);
        $criteria->compare('last_warning_time', $this->last_warning_time, true);
        $criteria->compare('is_defector', $this->is_defector);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}