<?php

/**
 * This is the model base class for the table "news".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "News".
 *
 * Columns in table "news" available as properties of the model,
 * followed by relations of table "news" available as properties of the model.
 *
 * @property string $id
 * @property string $text
 * @property string $issuer_id
 * @property string $time
 * @property string $title
 * @property integer $only_for_registered
 *
 * @property User $issuer
 */
abstract class BaseNews extends AActiveRecord
{

    public function getTextColumns()
    {
        return array();
    }

    public function tableName()
    {
        return 'news';
    }

    public static function label($n = 1)
    {
        return Yii::t('admin', 'News|News', $n);
    }

    public static function representingColumn()
    {
        return 'time';
    }

    public function rules()
    {
        return array(
            array('time', 'required'),
            array('only_for_registered', 'numerical', 'integerOnly'=>true),
            array('issuer_id', 'length', 'max'=>10),
            array('title', 'length', 'max'=>256),
            array('text', 'safe'),
            array('text, issuer_id, title, only_for_registered', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, text, issuer_id, time, title, only_for_registered', 'safe', 'on' => 'search'),
        );
    }

    public function relations()
    {
        return array(
            'issuer' => array(self::BELONGS_TO, 'User', 'issuer_id'),
        );
    }

    public function pivotModels()
    {
        return array(
        );
    }

    public function attributeLabels()
    {
        return array(
            'id' => Yii::t('app', 'ID'),
            'text' => Yii::t('app', 'Text'),
            'issuer_id' => null,
            'time' => Yii::t('app', 'Time'),
            'title' => Yii::t('app', 'Title'),
            'only_for_registered' => Yii::t('app', 'Only For Registered'),
            'issuer' => null,
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id, true);
        $criteria->compare('text', $this->text, true);
        $criteria->compare('issuer_id', $this->issuer_id);
        $criteria->compare('time', $this->time, true);
        $criteria->compare('title', $this->title, true);
        $criteria->compare('only_for_registered', $this->only_for_registered);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}