<?php

/**
 * This is the model base class for the table "user_event".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserEvent".
 *
 * Columns in table "user_event" available as properties of the model,
 * followed by relations of table "user_event" available as properties of the model.
 *
 * @property string $id
 * @property string $user_id
 * @property string $order_id
 * @property string $text
 * @property string $date
 *
 * @property User $user
 * @property Order $order
 */
abstract class BaseUserEvent extends AActiveRecord
{

    public function getTextColumns()
    {
        return array();
    }

    public function tableName()
    {
        return 'user_event';
    }

    public static function label($n = 1)
    {
        return Yii::t('admin', 'UserEvent|UserEvents', $n);
    }

    public static function representingColumn()
    {
        return 'text';
    }

    public function rules()
    {
        return array(
            array('user_id', 'required'),
            array('user_id, order_id', 'length', 'max'=>10),
            array('text, date', 'safe'),
            array('order_id, text, date', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, user_id, order_id, text, date', 'safe', 'on' => 'search'),
        );
    }

    public function relations()
    {
        return array(
            'user' => array(self::BELONGS_TO, 'User', 'user_id'),
            'order' => array(self::BELONGS_TO, 'Order', 'order_id'),
        );
    }

    public function pivotModels()
    {
        return array(
        );
    }

    public function attributeLabels()
    {
        return array(
            'id' => Yii::t('app', 'ID'),
            'user_id' => null,
            'order_id' => null,
            'text' => Yii::t('app', 'Text'),
            'date' => Yii::t('app', 'Date'),
            'user' => null,
            'order' => null,
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id, true);
        $criteria->compare('user_id', $this->user_id);
        $criteria->compare('order_id', $this->order_id);
        $criteria->compare('text', $this->text, true);
        $criteria->compare('date', $this->date, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}