<?php

/**
 * This is the model base class for the table "vacation".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Vacation".
 *
 * Columns in table "vacation" available as properties of the model,
 * followed by relations of table "vacation" available as properties of the model.
 *
 * @property string $id
 * @property string $user_id
 * @property string $date_from
 * @property string $date_to
 * @property string $reason
 *
 * @property User $user
 */
abstract class BaseVacation extends AActiveRecord
{

    public function getTextColumns()
    {
        return array();
    }

    public function tableName()
    {
        return 'vacation';
    }

    public static function label($n = 1)
    {
        return Yii::t('admin', 'Vacation|Vacations', $n);
    }

    public static function representingColumn()
    {
        return 'date_from';
    }

    public function rules()
    {
        return array(
            array('user_id', 'required'),
            array('user_id', 'length', 'max'=>10),
            array('date_from, date_to, reason', 'safe'),
            array('date_from, date_to, reason', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, user_id, date_from, date_to, reason', 'safe', 'on' => 'search'),
        );
    }

    public function relations()
    {
        return array(
            'user' => array(self::BELONGS_TO, 'User', 'user_id'),
        );
    }

    public function pivotModels()
    {
        return array(
        );
    }

    public function attributeLabels()
    {
        return array(
            'id' => Yii::t('app', 'ID'),
            'user_id' => null,
            'date_from' => Yii::t('app', 'Date From'),
            'date_to' => Yii::t('app', 'Date To'),
            'reason' => Yii::t('app', 'Reason'),
            'user' => null,
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id, true);
        $criteria->compare('user_id', $this->user_id);
        $criteria->compare('date_from', $this->date_from, true);
        $criteria->compare('date_to', $this->date_to, true);
        $criteria->compare('reason', $this->reason, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}