<?php

/**
 * This is the model base class for the table "update".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Update".
 *
 * Columns in table "update" available as properties of the model,
 * followed by relations of table "update" available as properties of the model.
 *
 * @property string $id
 * @property string $user_id
 * @property string $date
 * @property string $section
 *
 * @property User $user
 */
abstract class BaseUpdate extends AActiveRecord
{

    public function getTextColumns()
    {
        return array();
    }

    public function tableName()
    {
        return 'update';
    }

    public static function label($n = 1)
    {
        return Yii::t('admin', 'Update|Updates', $n);
    }

    public static function representingColumn()
    {
        return 'date';
    }

    public function rules()
    {
        return array(
            array('user_id, date, section', 'required'),
            array('user_id', 'length', 'max'=>10),
            array('section', 'length', 'max'=>32),
            array('id, user_id, date, section', 'safe', 'on' => 'search'),
        );
    }

    public function relations()
    {
        return array(
            'user' => array(self::BELONGS_TO, 'User', 'user_id'),
        );
    }

    public function pivotModels()
    {
        return array(
        );
    }

    public function attributeLabels()
    {
        return array(
            'id' => Yii::t('app', 'ID'),
            'user_id' => null,
            'date' => Yii::t('app', 'Date'),
            'section' => Yii::t('app', 'Section'),
            'user' => null,
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id, true);
        $criteria->compare('user_id', $this->user_id);
        $criteria->compare('date', $this->date, true);
        $criteria->compare('section', $this->section, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}